services:
  traefik:
    container_name: traefik
    platform: linux/amd64
    image: traefik:latest
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck"]
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 5s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/traefik/ssl:ro
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./traefik_dynamic.yaml:/etc/traefik/dynamic/traefik_dynamic.yaml:ro
    labels:
      - "traefik.enable=true"
    restart: unless-stopped
    networks:
      - traefik


# Add the nginx service
  nginx:
    image: shashwot/nginx-more
    container_name: nginx
    platform: linux/amd64
    labels:
      - "traefik.enable=true"   
    networks:
      - traefik
    restart: unless-stopped


networks:
  traefik:
    driver: bridge