################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  dashboard: true
  insecure: false

################################################################
# Enable Healthcheck
################################################################
ping: {}

################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false

################################################################
# Access Logging
################################################################
# enable Access logs
accessLog: {}
#Configuring Multiple Filters
# accessLog:
#   filters:    
#     statusCodes:
#       - "404"
#     retryAttempts: true
#     minDuration: "10ms"

################################################################
# Traefik Logging -  DEBUG, PANIC, FATAL, ERROR, WARN, and INFO (DEFAULT is ERROR)
################################################################
log:
  level: DEBUG

################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

################################################################
# Challenge HTTP
################################################################
certificatesResolvers:
  myresolver:
    acme:
      email: shashwot@gmail.com 
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

################################################################
# Challenge TLS
################################################################
# certificatesResolvers:
#   myresolver:
#     acme:
#       email: shashwot@gmail.com  
#       storage: /letsencrypt/acme.json
#       tlsChallenge: true
#         # # used during the challenge
#         # entryPoint: web

################################################################
# Challenege DNS
################################################################
# certificatesResolvers:
#   myresolver:
#     acme:
#       email: shashwot@gmail.com
#       storage: /letsencrypt/acme.json
#       dnsChallenge:
#         provider: digitalocean
#         delayBeforeCheck: 0