################################################################
# API and dashboard configuration
################################################################
api:
  # Dashboard
  dashboard: true
  insecure: false

################################################################
# Enable Healthcheck
################################################################
ping: {}

################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic/traefik_dynamic.yaml
    watch: true

################################################################
# Access Logging
################################################################
# enable Access logs
accessLog: {}
#Configuring Multiple Filters
# accessLog:
#   filters:
#     statusCodes:
#       - "404"
#     retryAttempts: true
#     minDuration: "10ms"

################################################################
# Traefik Logging -  DEBUG, PANIC, FATAL, ERROR, WARN, and INFO (DEFAULT is ERROR)
################################################################
log:
  level: INFO

################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      middlewares:
        - content-compress@file
        - https-redirect@file
        - secureHeaders@file
        - corsHeaders@file
################################################################
# Manual SSL
################################################################
tls:
  certificates:
    - certFile: /etc/traefik/ssl/cert.pem
      keyFile: /etc/traefik/ssl/key.pem
################################################################
# Challenge HTTP
################################################################
# certificatesResolvers:
#   myresolver:
#     acme:
#       email: shashwot@gmail.com
#       storage: /letsencrypt/acme.json
#       httpChallenge:
#         entryPoint: web
################################################################
# Challenge TLS
################################################################
# certificatesResolvers:
#   myresolver:
#     acme:
#       email: shashwot@gmail.com
#       storage: /letsencrypt/acme.json
#       tlsChallenge: true
#         # # used during the challenge
#         # entryPoint: web

################################################################
# Challenege DNS
################################################################
# certificatesResolvers:
#   myresolver:
#     acme:
#       email: shashwot@gmail.com
#       storage: /letsencrypt/acme.json
#       dnsChallenge:
#         provider: digitalocean
#         delayBeforeCheck: 0
